-- WinnyRay Nigeria Limited - Supabase Schema
-- This schema covers bookings, site content management, and future property listings.

-- 1. BOOKINGS & ENQUIRIES TABLE
-- Handles cleaning requests, quote requests, and real estate enquiries.
CREATE TABLE IF NOT EXISTS bookings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  client_name TEXT NOT NULL,
  client_email TEXT,
  client_phone TEXT NOT NULL,
  service_type TEXT NOT NULL, -- Format: "cleaning: Service Name" or "real-estate: Enquiry Type"
  address TEXT,
  city TEXT DEFAULT 'Kano',
  instructions TEXT,
  status TEXT DEFAULT 'pending', -- pending, contacted, completed, cancelled
  metadata JSONB DEFAULT '{}'::jsonb
);

-- 2. SITE SETTINGS & CONTENT TABLE
-- Stores manageable content like About Us, Privacy Policy, and Contact Info.
CREATE TABLE IF NOT EXISTS site_settings (
  id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  updated_at TIMESTAMPTZ DEFAULT now(),
  content JSONB NOT NULL DEFAULT '{
    "contact_info": {
      "address": "15 Bravo Close Zungeru by kwakwachi, Kano",
      "phone": "+234 703 698 1080, +234 813 473 9747, +234 907 772 7119",
      "email": "info@winnyray.com.ng",
      "working_hours": "Mon - Fri: 8:00 AM - 6:00 PM"
    },
    "about": {
      "title": "About WinnyRay Nigeria Limited",
      "content": "WinnyRay Nigeria Limited is a premier service provider based in Kano...",
      "mission": "To provide world-class cleaning and real estate services...",
      "vision": "To be the most trusted and preferred service provider in Nigeria."
    },
    "privacy_policy": {
      "title": "Privacy Policy",
      "content": "Your privacy is important to us...",
      "last_updated": "2026-04-11"
    }
  }'::jsonb
);

-- 3. PROPERTIES TABLE (Future Use)
-- For listing houses, apartments, and land.
CREATE TABLE IF NOT EXISTS properties (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT now(),
  title TEXT NOT NULL,
  description TEXT,
  price NUMERIC,
  location TEXT NOT NULL,
  category TEXT NOT NULL, -- sale, rent, lease
  type TEXT NOT NULL, -- house, apartment, land
  beds INTEGER,
  baths INTEGER,
  sqft NUMERIC,
  images TEXT[] DEFAULT '{}',
  features TEXT[] DEFAULT '{}',
  is_featured BOOLEAN DEFAULT false,
  status TEXT DEFAULT 'available' -- available, sold, rented
);

-- 4. USER PROFILES
-- Extends Supabase Auth with custom roles.
CREATE TABLE IF NOT EXISTS profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  full_name TEXT,
  role TEXT DEFAULT 'client', -- client, admin
  phone TEXT,
  created_at TIMESTAMPTZ DEFAULT now()
);

-- 5. SECURITY POLICIES (RLS)

-- Enable RLS on all tables
ALTER TABLE bookings ENABLE ROW LEVEL SECURITY;
ALTER TABLE site_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE properties ENABLE ROW LEVEL SECURITY;
ALTER TABLE profiles ENABLE ROW LEVEL SECURITY;

-- Storage Policies (Run these in SQL Editor)
-- Note: Ensure the 'site-assets' bucket is created first.
-- INSERT INTO storage.buckets (id, name, public) VALUES ('site-assets', 'site-assets', true);

-- Allow public to view assets
DROP POLICY IF EXISTS "Public View Assets" ON storage.objects;
CREATE POLICY "Public View Assets" ON storage.objects FOR SELECT USING (bucket_id = 'site-assets');

-- Allow admins to manage assets
DROP POLICY IF EXISTS "Admin Manage Assets" ON storage.objects;
CREATE POLICY "Admin Manage Assets" ON storage.objects FOR ALL USING (
  bucket_id = 'site-assets' AND 
  (
    EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') OR
    (auth.jwt() ->> 'email') IN ('sactechcomputers@gmail.com', 'sheriffdeenalade@gmail.com')
  )
);

-- Bookings Policies
DROP POLICY IF EXISTS "Allow public to insert bookings" ON bookings;
CREATE POLICY "Allow public to insert bookings" ON bookings FOR INSERT WITH CHECK (true);

DROP POLICY IF EXISTS "Allow admins to view bookings" ON bookings;
CREATE POLICY "Allow admins to view bookings" ON bookings FOR SELECT USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

DROP POLICY IF EXISTS "Allow admins to update bookings" ON bookings;
CREATE POLICY "Allow admins to update bookings" ON bookings FOR UPDATE USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin')
);

-- Site Settings Policies
DROP POLICY IF EXISTS "Allow public to view settings" ON site_settings;
CREATE POLICY "Allow public to view settings" ON site_settings FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admins to modify settings" ON site_settings;
CREATE POLICY "Allow admins to modify settings" ON site_settings FOR ALL USING (
  (auth.jwt() ->> 'email') IN ('sactechcomputers@gmail.com', 'sheriffdeenalade@gmail.com')
);

-- Properties Policies
DROP POLICY IF EXISTS "Allow public to view properties" ON properties;
CREATE POLICY "Allow public to view properties" ON properties FOR SELECT USING (true);

DROP POLICY IF EXISTS "Allow admins to manage properties" ON properties;
CREATE POLICY "Allow admins to manage properties" ON properties FOR ALL USING (
  EXISTS (SELECT 1 FROM profiles WHERE id = auth.uid() AND role = 'admin') OR
  (auth.jwt() ->> 'email') IN ('sactechcomputers@gmail.com', 'sheriffdeenalade@gmail.com')
);

-- Profiles Policies
DROP POLICY IF EXISTS "Users can view their own profile" ON profiles;
CREATE POLICY "Users can view their own profile" ON profiles FOR SELECT USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own profile" ON profiles;
CREATE POLICY "Users can update their own profile" ON profiles FOR UPDATE USING (auth.uid() = id);

DROP POLICY IF EXISTS "Admins can view all profiles" ON profiles;
CREATE POLICY "Admins can view all profiles" ON profiles FOR SELECT USING (
  (auth.jwt() ->> 'email') IN ('sactechcomputers@gmail.com', 'sheriffdeenalade@gmail.com')
);

-- 6. INITIAL DATA SEED
-- Insert default site settings if not exists
INSERT INTO site_settings (id, content) 
VALUES (1, '{
  "contact_info": {
    "address": "15 Bravo Close Zungeru by kwakwachi, Kano",
    "phone": "+234 703 698 1080, +234 813 473 9747, +234 907 772 7119",
    "email": "info@winnyray.com.ng",
    "working_hours": "Mon - Fri: 8:00 AM - 6:00 PM"
  },
  "social_links": {
    "facebook": "#",
    "instagram": "#",
    "twitter": "#"
  },
  "hero_slides": [
    {
      "title": "Pristine Spaces, Professional Care",
      "subtitle": "Premium Cleaning Services in Kano",
      "desc": "Experience the gold standard of cleanliness for your home and office.",
      "image": "https://images.unsplash.com/photo-1584622650111-993a426fbf0a?auto=format&fit=crop&q=80&w=1920",
      "link": "/cleaning",
      "btnText": "Cleaning Services"
    },
    {
      "title": "Exclusive Real Estate Listings",
      "subtitle": "Find Your Dream Home in Kano",
      "desc": "Discover premium properties in Nigeria''s most prestigious neighborhoods.",
      "image": "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&q=80&w=1920",
      "link": "/real-estate",
      "btnText": "Real Estate"
    }
  ],
  "services": {
    "cleaning": [
      {
        "title": "Residential Cleaning",
        "desc": "Standard, deep, and move-in/out cleaning for your home.",
        "image": "https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?auto=format&fit=crop&q=80&w=800",
        "features": ["Standard Cleaning", "Deep Cleaning", "Move-in/Out"]
      }
    ],
    "real_estate": [
      {
        "title": "Premium Real Estate",
        "desc": "Discover exclusive properties in Kano and beyond.",
        "image": "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=1000",
        "link": "/real-estate"
      }
    ]
  },
  "about": {
    "title": "About WinnyRay Nigeria Limited",
    "content": "WinnyRay Nigeria Limited is a premier service provider based in Kano, specializing in professional cleaning and luxury real estate. We are committed to excellence, integrity, and customer satisfaction.",
    "mission": "To provide world-class cleaning and real estate services that enhance the quality of life for our clients.",
    "vision": "To be the most trusted and preferred service provider in Nigeria.",
    "image": "https://images.unsplash.com/photo-1560179707-f14e90ef3623?auto=format&fit=crop&q=80&w=1000"
  },
  "privacy_policy": {
    "title": "Privacy Policy",
    "content": "Your privacy is important to us. This policy explains how we collect, use, and protect your personal information...",
    "last_updated": "April 10, 2026"
  }
}') ON CONFLICT (id) DO NOTHING;
